# Generated by Django 3.2.5 on 2021-07-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRoom',
        ),
    ]
